# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

# Note about adding a WF status badge: This Markdown example adds a status badge for a workflow with the name "Greet Everyone."
# The OWNER of the repository is the actions organization and the REPOSITORY name is hello-world.
# ![example workflow name](https://github.com/actions/hello-world/workflows/Greet%20Everyone/badge.svg)


name: Opt4J Build & Test

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Generate the test report
      run: ./gradlew jacocorootreport
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: ./build/reports/jacoco/rootReport.xml
    - name: Run codacy-analysis-cli
      uses: codacy/codacy-analysis-cli-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        max-allowed-issues: 400
